### ISSUE TITLE
Dinner

### ISSUE THREAD

**Issue by tcolehunter** [gotom22/PASTA-Data-Analysis#1]
We need to eat soon
@DrrBcn

**Comment by gotom22** [comment]
I for sure will have the cordon bleu

**Comment by DrrBcn** [comment]
Dinner is at 8pm ...

**Comment by tcolehunter** [comment]
![img_20150618_210015](https://cloud.githubusercontent.com/assets/12965471/8257428/d6261480-16ad-11e5-9194-bcade8cc644e.jpg)
